# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
sudo:                false
language:            r
cache:               packages
warnings_are_errors: true
dist:                trusty
r:
  - release
# - devel

addons:
  apt:
    update:          false
    packages:
#      - unixodbc-dev

r_github_packages:
  - jimhester/covr
  - tidyverse/readr
# - tidyverse/dplyr
# - jeroen/curl
# - r-lib/httr

after_success:
  - Rscript -e 'covr::coveralls()'

# apt_packages:
#   - r-cran-rodbc
#   - unixodbc-dev
