# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language:            r
cache:               packages
warnings_are_errors: true
os:                  linux
r:
  - release
# - devel

addons:
  apt:
    update:          false
    packages:
#      - unixodbc-dev

r_github_packages:
  - jimhester/covr
  - tidyverse/readr
  - OuhscBbmc/REDCapR
# - tidyverse/dplyr
# - jeroen/curl
# - r-lib/httr

after_success:
  - Rscript -e 'covr::coveralls()'

# apt_packages:
#   - r-cran-rodbc
#   - unixodbc-dev
